# Generated by Django 2.1.7 on 2019-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remain_coins',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
