# Generated by Django 2.1.7 on 2019-04-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_profile_remain_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='remain_coins',
            field=models.IntegerField(default=100),
        ),
    ]
