# Generated by Django 2.1.7 on 2019-04-12 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_type', models.CharField(choices=[('mc', 'Макулатура'), ('ir', 'Железо'), ('pl', 'Пластик'), ('gl', 'Стекло')], default=None, max_length=2)),
                ('weight', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trash', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
